name: deploy-to-lambda

on:
  push:
    branches: [main]
    paths:
      - '**.yaml'
      - '**.yml'

jobs:
  deploy_source:
    name: deploy lambda by push
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: config aws credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
          function_name: skills-function
          memory_size: 128
          timeout: 3
      - name: zip Lambda Function
        run: zip -r9 function_name.zip *
      - name: update code
        run: aws lambda update-function-code --function-name skills-function --zip-file fileb://function_name.zip